import { Router } from 'express';
import { getAll, getById, create, updateById, removeById, removeAll } from '../controllers/contactController.js';
const router = Router();
router.get('/', getAll);
router.get('/:id', getById);
router.post('/', create);
router.put('/:id', updateById);
router.delete('/:id', removeById);
router.delete('/', removeAll);
export default router;
